stages:
  - deps
  - run

deps:
  stage: deps
  image: ubuntu:latest
  script:
    - apt-get update

    # Setup PHP
    - apt-get install -y php-cli php-gd
    - curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
    # Setup NODE
    - apt-get install -y nodejs
    - npm install -g deobfuscator
    # Setup Python
    - apt-get install -y python3 python3-pip
    - python3 -m pip install --upgrade pip

# Job
run-bot:
  stage: run
  image: ubuntu:latest
  needs: ["deps"]
  parallel:
    matrix:
      - MAIL: "a@x.com"
      - MAIL: "b@y.com"
      - MAIL: "c@z.com"
  script:
    - |
      if [ -n "$KEY" ]; then
        export KEY="$KEY"
      else
        case "$API" in
          solverify) export KEY="$SOLVERIFY" ;;
          tertuyul)  export KEY="$TERTUYUL" ;;
          xevil)     export KEY="$XEVIL" ;;
          skibidixxx) export KEY="$SKIBIDI" ;;
          capsolver) export KEY="$CAPSOLVER" ;;
          multibot)  export KEY="$MULTIBOT" ;;
          gmxch)     export KEY="$GMXCH" ;;
          *)         export KEY="" ;;
        esac
      fi

      php run.php
  variables:
    CI: "1"
    AN: "0"
    BOT: $BOT
    AUTH: $AUTH
    API: $API
    KEY: $KEY
    login: ${LOGIN}
    mail: $MAIL
    pass: ${PASS}